[package]
name = "ring-queue"
version = "0.1.0"
authors = ["Kevin Moonen <moone140@umn.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
